// <auto-generated />
using System;
using Contoso.Expenses.Common.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contoso.Expenses.Common.Migrations
{
    [DbContext(typeof(ContosoExpensesWebContext))]
    partial class ContosoExpensesWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Contoso.Expenses.Common.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ApproverEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CostCenter")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Purpose")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Receipt")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SubmitterEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ExpenseId");

                    b.ToTable("Expense");
                });
#pragma warning restore 612, 618
        }
    }
}
