// <auto-generated />
using Contoso.Expenses.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contoso.Expenses.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Contoso.Expenses.API.Models.CostCenter", b =>
                {
                    b.Property<int>("CostCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApproverEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CostCenterName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SubmitterEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CostCenterId");

                    b.ToTable("CostCenters");
                });
#pragma warning restore 612, 618
        }
    }
}
